---
- name: install docker
  hosts: docker-nodes
  roles:
    - docker-installation
  run_once: true

- name: initialize docker swarm
  hosts: swarm-managers
  roles:
    - docker-swarm-init
  run_once: true

- name: add workers to the swarm
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker
  run_once: true

- name: Deploy stack of services  
  hosts: swarm-managers  
  roles:
    - docker-swarm-service

