version: "3.3"
services:
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - webstacknet 
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webstacknet

networks:
  webstacknet:
